### PR TITLE
Add lang="en" to <html>

### PR DESCRIPTION
**Pull request by jamiebuilds**
Oops meant to leave a description. 

Just opening this PR in response to a report on the Yarn website about a11y: https://github.com/yarnpkg/website/issues/197

### CODE REVIEW

**Comment by XhmikosR** [comment]
Actually this can be closed since I include this in #121.

**Comment by octref** [comment]
Would fix #130.

@XhmikosR I see you have a lot of PRs in this repo, but @mdo seems not maintaining this anymore. Are you working on a fork? Anyway we can get your changes merged?

**Comment by XhmikosR** [comment]
It's up to @mdo. The patches are still valid, but I don't plan on forking; I'd rather ping @mdo so that we merge things here.

**Comment by XhmikosR** [comment]
Picked up in the v4-dev branch, it'll be in the next release. Thanks!

**Pull request closed without merging**
