### PR TITLE
Use parameters from URL fragment

### PR DESCRIPTION
**Pull request by patryk**
Twitter thread: https://twitter.com/epatryk/status/1255814124816289795

### CODE REVIEW

**Comment by XhmikosR** [comment]
Hey, thanks for the PR!

That being said, we need to be extra careful not to break existent uses.

So, while this works, it's a breaking change AFAICT.

**Comment by patryk** [comment]
Do local testing, but I think it should work even with existing embeds.

**Comment by XhmikosR** [comment]
I think I got the cache to work so this might not be needed after all :)

I used `ghbtns.com/github-btn.html?*` as the URL and it seems now it's cached regardless of the queries.

**Comment by patryk** [comment]
I still think you'd get even better results doing a redirect.
Now:
```
https://ghbtns.com/github-btn.html?param=1
https://ghbtns.com/github-btn.html?param=2
```
are two different cache objects (cache hit ratio <100%, likely 50-70%), but the redirect done with Page Rule is generated on the edge (no latency and no hitting the origin), then
```
https://ghbtns.com/github-btn.html#param=1
https://ghbtns.com/github-btn.html#param=2
```
are just one file `https://ghbtns.com/github-btn.html` from the browser's point of view.

Then this PR reads data you need from URL fragment, which is still accessible from JavaScript. Because you are hosing the code, you can make the change that will automatically apply to all existing users.

End result: 100% cache hit ratio.

Obviously, in the end it's up to you.

**Comment by XhmikosR** [comment]
First of all, I really appreciate you taking the time to make a PR 🙂

It's just that I'm trying to make one change at a time. Also, I'm not a fan of adding a redirect, unless we really need to. With my current solution, which doesn't involve any code changes or a redirect, our cache ratio went from 0.4% to ~88%. Now, it might not be close to 100%, but I think it's a pretty good improvement!

Our free plan allows for 3 Page Rules, but I think it is enough right now.

Here is what I have currently deployed:

Screenshot_2020-04-30

I plan to experiment with adding an Edge Cache TTL of 2 hours; I'm not sure of the effect this will have.

**Comment by patryk** [comment]
You already have it cached for 2 hours, unless the origin sends `Cache-Control` header specifying otherwise.
https://support.cloudflare.com/hc/en-us/articles/200172516-Understanding-Cloudflare-s-CDN#h_51422705-42d0-450d-8eb1-5321dcadb5bc

You may actually benefit from raising the Edge Cache TTL either with `Cache-Control` (I don't think GitHub Pages allow to control this) or setting `Edge Cache TTL` Page Rule (note: only one rule will match the URL, but you can set several settings inside the same rule).

**Comment by XhmikosR** [comment]
>You already have it cached for 2 hours, unless the origin sends Cache-Control header specifying otherwise.

The origin (GitHub Pages) send `max-age=600`.

**Comment by patryk** [comment]
> Here is what I have currently deployed:
> 
> Screenshot_2020-04-30

Because both rules have same settings, you may simplify it by just matching:
`https://ghbtns.com/github-btn.html*`

**Comment by XhmikosR** [comment]
True, thanks for the suggestion :) It was two rules because I added the one without the query second.

So, basically this caches everything for 2 hours on Cloudflare's POPs, right? Edge Cache TTL is moot then?

I'm still hesitant about the 403 HTTP error code being cached, though. We'll see how it goes.

**Comment by XhmikosR** [comment]
Actually, scratch that, I need coffee again 😛 This file is not related to the GitHub API. We should be OK, I think.

**Comment by patryk** [comment]
> The only thing I'm not 100% sure about is the 403 error code case, which one might hit if they hit the GitHub API rate limit.

That is separate issue from the one we discuss here, but I invite you to play with Cloudflare Workers. You may proxy GitHub API calls through it (and they can be cached). Free if < 100k requests/day.

**Comment by XhmikosR** [comment]
We have 1.7M requests in the last 24 hours :)

I think we should be fine with the current rules. Maybe I'll play with Edge Cache TTL later, but one change at a time.

**Comment by patryk** [comment]
> So, basically this caches everything for 2 hours on Cloudflare's POPs, right? Edge Cache TTL is moot then?

If you don't override with `Edge Cache TTL` Page Rule explicitly, whatever is sent by GitHub Pages will dictate caching expiry (10 minutes in this case).

**Comment by XhmikosR** [comment]
Perfect, then I will definitely specify Edge Cache TTL 2 hours.

Thanks for your help!

**Comment by patryk** [comment]
You welcome!

**Comment by XhmikosR** [comment]
We are now getting a ~90% cache ratio which I think it's pretty good.

I'm going to close this PR @patryk, but thanks again for your help!

**Pull request closed without merging**
